In [1]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/E-commerce Smart Search & Recommendation Engine

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/E-commerce Smart Search & Recommendation Engine

In [3]:
import shutil
from pathlib import Path

# Define the source path from your Google Drive
source_path = Path('kaggle.json')

# Define the destination path in the Colab system environment
kaggle_dir = Path.home() / '.kaggle'
dest_path = kaggle_dir / 'kaggle.json'

# Create the hidden .kaggle directory if it doesn't exist
kaggle_dir.mkdir(parents=True, exist_ok=True)

# Copy the json file from Drive to the hidden system directory
shutil.copy(source_path, dest_path)

# Set the required permissions (read/write for owner only) so Kaggle accepts it
dest_path.chmod(0o600)

print(f"Kaggle credentials successfully set up at: {dest_path}")

Kaggle credentials successfully set up at: /root/.kaggle/kaggle.json

In [4]:
import zipfile
from pathlib import Path

project_dir = Path('.')
data_dir = project_dir / 'data'
zip_path = project_dir / 'amazon-sales-dataset.zip'


data_dir.mkdir(exist_ok=True)


if not zip_path.exists():
    !kaggle datasets download -d karkavelrajaj/amazon-sales-dataset -p .


with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(data_dir)

print(f"Dataset successfully extracted to: {data_dir.resolve()}")

Dataset successfully extracted to: /content/drive/MyDrive/E-commerce Smart Search & Recommendation Engine/data

In [18]:
import pandas as pd

# Join the directory path with the exact CSV file name
csv_path = data_dir / 'amazon.csv'

# Verify the file exists before loading
if csv_path.exists():
    amazon_df= pd.read_csv(csv_path)

    # Display the first 5 rows to confirm it loaded correctly
    display(amazon_df.head())
else:
    print(f"Error: Could not find the dataset at {csv_path}")

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [6]:
amazon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

In [7]:
amazon_df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [8]:
amazon_df.duplicated().sum()

np.int64(0)

In [21]:
amazon_df.duplicated(subset=['product_name','about_product']).sum()

np.int64(118)

In [22]:
amazon_df.drop_duplicates(subset=['product_name','about_product'],inplace=True)

In [24]:
amazon_df.duplicated(subset=['product_name','about_product']).sum()

np.int64(0)

In [25]:
amazon_df['product_content']=amazon_df['product_name']+' '+amazon_df['about_product']

In [26]:
amazon_df.duplicated(subset=['product_content']).sum()

np.int64(0)

In [27]:
amazon_df['product_content'].values

array(["Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey) High Compatibility : Compatible With iPhone 12, 11, X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 Plus,iPhone 6s/6s Plus,iPhone 6/6 Plus,iPhone 5/5s/5c/se,iPad Pro,iPad Air 1/2,iPad mini 1/2/3,iPod nano7,iPod touch and more apple devices.|Fast Charge&Data Sync : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|Durability : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|High Security Level : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.|WARRANTY: 12 months warranty and friendly customer services, ensures the long-time enjoyment of your purchase. If you meet any question or problem, please don't hesitate to contact us.",
       'Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black) Compatible with all Type C enabled devices, be it an android smartphone (Mi, Samsung, Oppo, Vivo, Realme, OnePlus, etc), tablet, laptop (Macbook, Chromebook, etc)|Supports Quick Charging (2.0/3.0)|Unbreakable – Made of special braided outer with rugged interior bindings, it is ultra-durable cable that won’t be affected by daily rough usage|Ideal Length – It has ideal length of 1.5 meters which is neither too short like your typical 1meter cable or too long like a 2meters cable|Supports maximum 3A fast charging and 480 Mbps data transfer speed|6 months manufacturer warranty from the date of purchase',
       "Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices 【 Fast Charger& Data Sync】-With built-in safety proctections and four-core copper wires promote maximum signal quality and strength and enhance charging & data transfer speed with up to 480 mb/s transferring speed.|【 Compatibility】-Compatible with iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS devices.|【 Sturdy & Durable】-The jacket and enforced connector made of TPE and premium copper, are resistant to repeatedly bending and coiling.|【 Ultra High Quality】: According to the experimental results, the fishbone design can accept at least 20,000 bending and insertion tests for extra protection and durability. Upgraded 3D aluminum connector and exclusive laser welding technology, which to ensure the metal part won't break and also have a tighter connection which fits well even with a protective case on and will never loose connection.|【 Good After Sales Service】-Our friendly and reliable customer service will respond to you within 24 hours ! you can purchase with confidence,and every sale includes a 365-day worry-free Service to prove the importance we set on quality.",
       ...,
       'Bajaj Majesty RX10 2000 Watts Heat Convector Room Heater (White, ISI Approved) International design and styling|Two heat settings 1000 W and 2000 W. Rated Voltage : 230 V|Adjustable thermostat for desirable temperature|Fan forced hot air circulation|Cool touch housing with built in handle|Two way installation- vertical and horizontal|Heater in winter, personal fan in summer',
       'Havells Ventil Air DSP 230mm Exhaust Fan (Pista Green) Fan sweep area: 230 MM ; Noise level: (40 - 45) dB; Fan body dimension (Length x Width x Depth): 290MM x 290MM x 200MM|With bird guard to protect the fan in running condition, Air flow rate: 510 cmh , Speed: 1350 RPM , Sweep size: 230 mm , Guard: 29 Spokes. Rated frequency : 50 Hz. Pull cord : No|Powder coated metallic finish, Adjustable upward and downward tilt mechanism: No|Sturdy steel bird guard with specially designed metal blade|For any functional defect, please reach out to customer care team @ Email: customercare@h',
       'Borosil Jumbo 1000-Watt Grill Sandwich Maker (Black) Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W Power for Faster Grilling|Makes 2 Sandwiches in minutes;Stainless Steel Mirror Finish Body; Easy to use;Easy to clean coated plates|Auto-lock latch;Larger deep ribbed grill plates for Krisp grilling|Rubber feet to avoid slipping on Countertop;Indicator Display.|Material Type: Plastic|Suitable for gifting on Diwali and other special occasions.'],
      dtype=object)

In [28]:
def clean_ecommerce_text(content):
    cleaned = re.sub('[^a-zA-Z0-9]', ' ', str(content))
    cleaned = cleaned.lower()
    cleaned = [word for word in cleaned.split() if word not in stopwords.words('english')]
    return ' '.join(cleaned)

In [29]:
amazon_df['clean_content'] = amazon_df['product_content'].apply(clean_ecommerce_text)

In [30]:
amazon_df['clean_content'].values

array(['wayona nylon braided usb lightning fast charging data sync cable compatible iphone 13 12 11 x 8 7 6 5 ipad air pro mini 3 ft pack 1 grey high compatibility compatible iphone 12 11 x xsmax xr iphone 8 8 plus iphone 7 7 plus iphone 6s 6s plus iphone 6 6 plus iphone 5 5s 5c se ipad pro ipad air 1 2 ipad mini 1 2 3 ipod nano7 ipod touch apple devices fast charge data sync charge sync simultaneously rapid speed compatible charging adaptor multi port charging station power bank durability durable nylon braided design premium aluminum housing toughened nylon fiber wound tightly around cord lending superior durability adding bit flexibility high security level designed fully protect device damaging excessive current copper core thick multilayer shielding anti interference protective circuit equipment warranty 12 months warranty friendly customer services ensures long time enjoyment purchase meet question problem please hesitate contact us',
       'ambrane unbreakable 60w 3a fast charging 1 5m braided type c cable smartphones tablets laptops type c devices pd technology 480mbps data sync quick charge 3 0 rct15a black compatible type c enabled devices android smartphone mi samsung oppo vivo realme oneplus etc tablet laptop macbook chromebook etc supports quick charging 2 0 3 0 unbreakable made special braided outer rugged interior bindings ultra durable cable affected daily rough usage ideal length ideal length 1 5 meters neither short like typical 1meter cable long like 2meters cable supports maximum 3a fast charging 480 mbps data transfer speed 6 months manufacturer warranty date purchase',
       'sounce fast phone charging cable data sync usb cable compatible iphone 13 12 11 x 8 7 6 5 ipad air pro mini ios devices fast charger data sync built safety proctections four core copper wires promote maximum signal quality strength enhance charging data transfer speed 480 mb transferring speed compatibility compatible iphone 13 12 11 x 8 7 6 5 ipad air pro mini ios devices sturdy durable jacket enforced connector made tpe premium copper resistant repeatedly bending coiling ultra high quality according experimental results fishbone design accept least 20 000 bending insertion tests extra protection durability upgraded 3d aluminum connector exclusive laser welding technology ensure metal part break also tighter connection fits well even protective case never loose connection good sales service friendly reliable customer service respond within 24 hours purchase confidence every sale includes 365 day worry free service prove importance set quality',
       ...,
       'bajaj majesty rx10 2000 watts heat convector room heater white isi approved international design styling two heat settings 1000 w 2000 w rated voltage 230 v adjustable thermostat desirable temperature fan forced hot air circulation cool touch housing built handle two way installation vertical horizontal heater winter personal fan summer',
       'havells ventil air dsp 230mm exhaust fan pista green fan sweep area 230 mm noise level 40 45 db fan body dimension length x width x depth 290mm x 290mm x 200mm bird guard protect fan running condition air flow rate 510 cmh speed 1350 rpm sweep size 230 mm guard 29 spokes rated frequency 50 hz pull cord powder coated metallic finish adjustable upward downward tilt mechanism sturdy steel bird guard specially designed metal blade functional defect please reach customer care team email customercare h',
       'borosil jumbo 1000 watt grill sandwich maker black brand borosil specification 23v 5hz 1 w power faster grilling makes 2 sandwiches minutes stainless steel mirror finish body easy use easy clean coated plates auto lock latch larger deep ribbed grill plates krisp grilling rubber feet avoid slipping countertop indicator display material type plastic suitable gifting diwali special occasions'],
      dtype=object)

In [63]:
vectorizer = TfidfVectorizer(max_df=90, min_df=2)
tfidf_matrix = vectorizer.fit_transform(amazon_df['clean_content'])

In [64]:
tfidf_matrix.shape

(1347, 5760)

In [65]:
def search_products(query: str, top_n: int = 5) -> None:
    """
    Search for products using a text query.
    """
    # 1. Convert the user query into numbers (vector) using our vectorizer.
    # It changes the text into a row of 10190 numbers.
    query_vec = vectorizer.transform([query])

    # 2. Calculate the similarity between the user query and all products.
    # .flatten() makes the result a simple 1D list.
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()

    # 3. Sort products from highest to lowest similarity and get the best results.
    top_indices = similarities.argsort()[-top_n:][::-1]

    print(f"Search results for: '{query}'\n" + "="*50)

    # 4. Print the results.
    for idx in top_indices:
        # Check if there is a real match (similarity is greater than 0).
        if similarities[idx] > 0:
            print(f"Similarity Score: {similarities[idx]:.2f}")
            # Print the product name from the dataframe.
            print(f"Product: {amazon_df['product_name'].iloc[idx]}")
            print("-" * 50)
        else:
            print("No matching products found.")
            break

# Test the search function
search_products("fast charging cable iphone 13")

Search results for: 'fast charging cable iphone 13'
==================================================
Similarity Score: 0.69
Product: REDTECH USB-C to Lightning Cable 3.3FT, [Apple MFi Certified] Lightning to Type C Fast Charging Cord Compatible with iPhone 14/13/13 pro/Max/12/11/X/XS/XR/8, Supports Power Delivery - White
--------------------------------------------------
Similarity Score: 0.59
Product: OpenTech® Military-Grade Tempered Glass Screen Protector Compatible for iPhone 13/13 Pro / 14 with Edge to Edge Coverage and Easy Installation kit (6.1 Inches)
--------------------------------------------------
Similarity Score: 0.55
Product: POPIO Tempered Glass Compatible for iPhone 13 / iPhone 13 Pro/iPhone 14 (Transparent) Edge to Edge Full Screen Coverage with Installation Kit, Pack of 2
--------------------------------------------------
Similarity Score: 0.49
Product: ESR USB C to Lightning Cable, 10 ft (3 m), MFi-Certified, Braided Nylon Power Delivery Fast Charging for iPhone 14/14 Plus/14 Pro/14 Pro Max, iPhone 13/12/11/X/8 Series, Use with Type-C Chargers, Black
--------------------------------------------------
Similarity Score: 0.47
Product: iPhone Original 20W C Type Fast PD Charger Compatible with I-Phone13/13 mini/13pro/13 pro Max I-Phone 12/12 Pro/12mini/12 Pro Max, I-Phone11/11 Pro/11 Pro Max 2020 (Only Adapter)
--------------------------------------------------

In [68]:
def recommend_products(product_index: int, top_n: int = 5) -> None:
    """
    Recommend similar products based on a chosen product.
    """
    # 1. Get the vector of the selected product from our matrix.
    # This represents the features of the product the user is viewing.
    target_vec = tfidf_matrix[product_index]

    # 2. Calculate the similarity between this product and all other products.
    similarities = cosine_similarity(target_vec, tfidf_matrix).flatten()

    # 3. Sort the results. We take top_n + 1 because the product itself will be a 100% match.
    # We use [1:] to skip the first result (the exact same product).
    top_indices = similarities.argsort()[-(top_n + 1):][::-1][1:]

    # Get the name of the target product for the print statement.
    target_name = amazon_df['product_name'].iloc[product_index]
    print(f"Because you viewed: '{target_name[:50]}...'\nWe recommend:\n" + "="*50)

    # 4. Print the recommended products.
    for idx in top_indices:
        print(f"Similarity Score: {similarities[idx]:.2f}")
        print(f"Product: {amazon_df['product_name'].iloc[idx]}")
        print("-" * 50)

# Test the recommendation function using product at index 0
recommend_products(0)

Because you viewed: 'Wayona Nylon Braided USB to Lightning Fast Chargin...'
We recommend:
==================================================
Similarity Score: 0.97
Product: Wayona Nylon Braided Usb Syncing And Charging Cable Sync And Charging Cable For Iphone, Ipad (3 Ft, Black) - Pack Of 2
--------------------------------------------------
Similarity Score: 0.95
Product: Wayona Nylon Braided (2 Pack) Lightning Fast Usb Data Cable Fast Charger Cord For Iphone, Ipad Tablet (3 Ft Pack Of 2, Grey)
--------------------------------------------------
Similarity Score: 0.95
Product: Wayona Nylon Braided 3A Lightning to USB A Syncing and Fast Charging Data Cable for iPhone, Ipad (3 FT Pack of 1, Black)
--------------------------------------------------
Similarity Score: 0.75
Product: Wayona Usb Nylon Braided Data Sync And Charging Cable For Iphone, Ipad Tablet (Red, Black)
--------------------------------------------------
Similarity Score: 0.74
Product: Wayona Nylon Braided 2M / 6Ft Fast Charge Usb To Lightning Data Sync And Charging Cable For Iphone, Ipad Tablet (6 Ft Pack Of 1, Grey)
--------------------------------------------------

In [70]:
project_dir = Path('.')

In [69]:
!pip install -q streamlit
!npm install localtunnel

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 15.8 MB/s eta 0:00:00
⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴
added 22 packages in 5s
⠴
⠴3 packages are looking for funding
⠴  run `npm fund` for details
⠴

In [77]:
import streamlit as st
import os
import sys
current_dir = os.getcwd()
sys.path.append(current_dir)

In [82]:
# 1. Run Streamlit in the background with correct nested quotes around the path
get_ipython().system_raw("streamlit run '/content/drive/MyDrive/E-commerce Smart Search & Recommendation Engine/E_app.py' --server.port 8501 --server.address 0.0.0.0 &")

# 2. Wait a few seconds to ensure Streamlit starts
import time
time.sleep(3)

# 3. Start Cloudflare tunnel
!wget -q -nc https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
!./cloudflared-linux-amd64 tunnel --url http://localhost:8501

2026-10-20T09:24:36Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-10-20T09:24:36Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-10-20T09:24:39Z INF +--------------------------------------------------------------------------------------------+
2026-10-20T09:24:39Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-10-20T09:24:39Z INF |  https://howard-departure-vacations-hawaiian.trycloudflare.com                             |
2026-10-20T09:24:39Z INF +--------------------------------------------------------------------------------------------+
2026-10-20T09:24:39Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-10-20T09:24:39Z INF Version 2026.10.1 (Checksum 3bfc539f45d2620c71debb7a86be0efa737ed5ccbad9eb85c787116900e5c586)
2026-10-20T09:24:39Z INF GOOS: linux, GOVersion: go1.27.2, GoArch: amd64
2026-10-20T09:24:39Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-10-20T09:24:39Z INF cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configure-tunnels/local-management/as-a-service/
2026-10-20T09:24:39Z INF Generated Connector ID: e836f043-5b7a-4e28-a5b0-107e329e20c6
2026-10-20T09:24:39Z INF Initial protocol quic
2026-10-20T09:24:39Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-10-20T09:24:39Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026/10/20 09:24:39 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-10-20T09:24:39Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-10-20T09:24:39Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-10-20T09:24:39Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-10-20T09:24:39Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.200.193
2026-10-20T09:24:40Z INF Registered tunnel connection connIndex=0 connection=da6781c2-7421-43c3-82a3-cf57e446eea0 event=0 ip=198.41.200.193 location=atl15 protocol=quic
2026-10-20T09:24:45Z INF +-------------------------------------------------------------------------------------+
2026-10-20T09:24:45Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-10-20T09:24:45Z INF +-------------------------------------------------------------------------------------+
2026-10-20T09:24:45Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-10-20T09:24:45Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-10-20T09:24:45Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-10-20T09:24:45Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-10-20T09:24:45Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-10-20T09:24:45Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-10-20T09:24:45Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-10-20T09:24:45Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-10-20T09:24:45Z INF |                                                                                     |
2026-10-20T09:24:45Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-10-20T09:24:45Z INF +-------------------------------------------------------------------------------------+
2026-10-20T09:24:45Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=5be73900-6f5d-4f11-9fb8-b4cb6354c96c status=pass target=region1.v2.argotunnel.com
2026-10-20T09:24:45Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=5be73900-6f5d-4f11-9fb8-b4cb6354c96c status=pass target=region2.v2.argotunnel.com
2026-10-20T09:24:45Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=5be73900-6f5d-4f11-9fb8-b4cb6354c96c status=pass target=region1.v2.argotunnel.com
2026-10-20T09:24:45Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=5be73900-6f5d-4f11-9fb8-b4cb6354c96c status=pass target=region2.v2.argotunnel.com
2026-10-20T09:24:45Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=5be73900-6f5d-4f11-9fb8-b4cb6354c96c status=pass target=region1.v2.argotunnel.com
2026-10-20T09:24:45Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=5be73900-6f5d-4f11-9fb8-b4cb6354c96c status=pass target=region2.v2.argotunnel.com
2026-10-20T09:24:45Z INF precheck component="Cloudflare API" details="API is reachable" run_id=5be73900-6f5d-4f11-9fb8-b4cb6354c96c status=pass target=api.cloudflare.com:443
2026-10-20T09:24:45Z INF precheck complete hard_fail=false run_id=5be73900-6f5d-4f11-9fb8-b4cb6354c96c suggested_protocol=quic
2026-10-20T09:30:15Z INF Initiating graceful shutdown due to signal interrupt ...
2026-10-20T09:30:16Z INF Retrying connection in up to 2s connIndex=0 event=0 ip=198.41.200.193
2026-10-20T09:30:16Z ERR Connection terminated connIndex=0
2026-10-20T09:30:16Z ERR no more connections active and exiting
2026-10-20T09:30:16Z INF Tunnel server stopped
2026-10-20T09:30:16Z INF Metrics server stopped

In [84]:
pip install pipreqs

Collecting pipreqs
  Downloading pipreqs-0.4.13-py2.py3-none-any.whl.metadata (7.4 kB)
Collecting docopt (from pipreqs)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting yarg (from pipreqs)
  Downloading yarg-0.1.10-py2.py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from yarg->pipreqs) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->yarg->pipreqs) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->yarg->pipreqs) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->yarg->pipreqs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->yarg->pipreqs) (2026.7.22)
Downloading pipreqs-0.4.13-py2.py3-none-any.whl (33 kB)
Downloading yarg-0.1.10-py2.py3-none-any.whl (13 kB)
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13781 sha256=672d49ba30babe0b2b47e6b898341b6f97b8e6aba06114fab5bb68533d684080
  Stored in directory: /root/.cache/pip/wheels/0b/1d/03/175286677fb5a1341cc3e4755bf8ec0ed08f3329afd67446b0
Successfully built docopt
Installing collected packages: docopt, yarg, pipreqs
Successfully installed docopt-0.6.2 pipreqs-0.4.13 yarg-0.1.10

In [86]:
!pipreqs . --force

WARNING: Import named "pandas" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "pandas" was resolved to "pandas:3.0.6" package (https://pypi.org/project/pandas/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "scikit_learn" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "scikit_learn" was resolved to "scikit-learn:1.9.1" package (https://pypi.org/project/scikit-learn/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in ./requirements.txt